{{- if not .Values.canary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
{{- end }}
